{% set name = "tstrait" %}
{% set version = "0.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tstrait-{{ version }}.tar.gz
  sha256: 49d5f96b0535fd662d3458fb487860f23cdad1d253738ec0105736a9b35b8139

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools
    - setuptools-scm
    - pip
  run:
    - python >=3.8
    - numpy >=1.20.3
    - numba >=0.57.0
    - pandas >=1.0
    - tskit >=0.5.5

test:
  imports:
    - tstrait

about:
  home: https://tskit.dev/tstrait/
  summary: Quantitative trait simulation on tskit tree sequences
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jeromekelleher
