{% set name = "tstrait" %}
{% set version = "0.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/tstrait-{{ version }}.tar.gz
  sha256: 6c7e4b0f8139a9090d2132d37f5225d4edf6c8027bc38e16a4a78db8fea0ae78

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.20.3
    - numba >=0.57.0
    - pandas >=1.0
    - tskit >=0.5.5

test:
  requires:
    - python {{ python_min }}
  imports:
    - tstrait

about:
  home: https://tskit.dev/tstrait/
  summary: Quantitative trait simulation on tskit tree sequences
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jeromekelleher
    - petrelharp
